name = "JEPAWorldState"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["JEPA Julia Agent Team"]
version = "0.1.0"

[deps]
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a6"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
JuliaInterpreter = "aa1ae85d-cber-53b7-b16e-c1c6e23e27b3"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1ber-d699-11e9-0d63-a587385d3b93"

[compat]
julia = "1.9"
